version: 0.1
phases:
  install:
    commands:
      - echo run npm install
      - npm install
  build:
    commands:
      - echo run Prod build
      - npm run build -- --base-href $BASE_HREF/ --output-path=dist/$BASE_HREF
      - mkdir config
      - echo '{"name": "prod", "production": true, "settings": {"backend": "api.myapp.com"}}' > config/environment.json
      - cp -R config/ dist/$BASE_HREF
  post_build:
    commands:
      - aws s3 cp --recursive dist/ s3://$SITE_BUCKET/
artifacts:
  type: zip
  files:
      - '**/*'
  discard-paths: yes
  base-directory: dist
